services:
  api:
    build: .
    container_name: card-api-dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - TORCH_NUM_THREADS=2
      - TORCH_INTEROP_THREADS=1
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
    command: >
      uvicorn index:app
      --host 0.0.0.0
      --port 8000
      --workers 4
